print("Seja bem vindo insira seus dados para continuar.")
print("________________________________________________")
nome = input("insira seu nome: ")
print("................................................")
idade = int(input("Insira sua idade: "))
print("................................................")
print(f"Bem vindo {nome} sua idade é {idade} anos.")
print("................................................")
print(f"Muito obrigado por inserir seus dados {nome}.")
print("________________________________________________")
